### PR TITLE
Fix TGS-REQ AES formating

### LINKED ISSUE #35: Wrong format for AES-encrypted tgsrep?
Doing:
```
> rubeus.exe kerberoast /format:hashcat /aes
```
... produces AES256 hashes in the format:
```
$krb5tgs$18$*[username]$[domain]$[spn]*$[checksum]$[edata]
```

Feeding this to hashcat (v5.1.0) results in an error:
```
~> hashcat -m 19700 -o cracked.txt -a 0 krb5tgs.txt password.txt

Hashfile 'krb5tgs.txt' on line 1 ($krb5t...3bc0e660c3164355a02806c3d248afc0): Separator unmatched
No hashes loaded.
```

Looking at [the corresponding hashcat module](https://github.com/hashcat/hashcat/blob/master/src/modules/module_19700.c#L138), the expected format is: 

```
$krb5tgs$18$[username]$[domain]$*[spn]*$[checksum]$[edata]
```

Manually updating the hash from Rubeus results in another error
```
~> hashcat -m 19700 -o cracked.txt -a 0 krb5tgs2.txt password.txt

Hashfile 'krb5tgs2.txt' on line 1 ($krb5t...3bc0e660c3164355a02806c3d248afc0): Token length exception
No hashes loaded.
```

Apparently hashcat expects the [`checksum` to be exactly 24 chars wide](https://github.com/hashcat/hashcat/blob/master/src/modules/module_19700.c#L166). 

Manually moving the `$` separator 8 chars up makes hashcat load the hash, but doesn't succeed in cracking it. I suspect we need to re-calculate the checksum over the [`cipherText`](https://github.com/GhostPack/Rubeus/blob/master/Rubeus/lib/Roast.cs#L740) part, but I'm a bit out of my depth here 😄

### PR DESCRIPTION
**Pull request by iontodd**
Fixes #35 by treating RC4 and AES checksums differently. 

In addition, the AES format has been modified so that the SPN is enclosed in asterisks, rather than the username, realm and SPN. This is appears to be inline with what Hashcat is expecting, and what GetUserSPNs produces.

### CODE REVIEW

**Comment by coffeegist** [comment]
Tested this pull today, it doesn't seem to work with hashcat. However, I haven't been able to confirm if it's a hashcat issue or Rubeus issue. @iontodd were you able to crack hashes with hashcat from this format?

**Comment by HarmJ0y** [comment]
I don't have a Hashcat instance handle so I'm not able to test the AES format. @iontodd can you confirm that the hashes do crack?

**Comment by iontodd** [comment]
@coffeegist Did you come right with this? We spoke offline and if I recall you could get Hashcat to load in a $18, but it would not crack. This was even though you had cracked the password trivially with an AS-Rep Roast?

I've rechecked my side and its working with both GetTGSRepHash methods (TGT blog + without TGT), against simple hashes on the latest version of Hashcat.

**Comment by iontodd** [comment]
@coffeegist Did you come right with this? We spoke offline and if I recall you could get Hashcat to load in a $18, but it would not crack. This was even though you had cracked the password trivially with an AS-Rep Roast?

I've rechecked my side and its working with both GetTGSRepHash methods (TGT blog + without TGT), against simple hashes on the latest version of Hashcat.

EDIT: Whoops, closed this by mistake.

**Comment by HarmJ0y** [comment]
Landed, if there are still issues with this feel free to reopen.

**Pull request merged**
