### PR TITLE
fixes for #102 and #103

### PR DESCRIPTION
**Pull request by l0ss**
These changes fix the issues i ran into as described in #102 and #103.

I'm a little unsure about how I've handled the missing password last reset value (i.e. i set it to "two days ago") but everything else is basically just adding some checks that the thing exists in the dictionary before you try to use it.

### CODE REVIEW

**Comment by 0xe7** [comment]
A couple of notes:

- line 391 looks like a debug message still in there
- line 401 probably cleaner to check for `DateTime.MinValue` rather than the string
- the *else* statements for `logoncount` (lines 475-478) and `badpwdcount` (lines 483-486) are unnecessary
- for the key check for `lastlogon`, `lastlogoff` and `pwdlastset`, it may be cleaner to put it within the same conditional, like this:

```
if (userObject.ContainsKey("lastlogon") && ((DateTime)userObject["lastlogon"] != DateTime.MinValue))
```

**Comment by l0ss** [comment]
i fixed up the first three bullet points above but have left the fourth as-is. 

I'm on the wrong computer to double-check right now but i'm like 95% certain that if we do it like that it will always try to evaluate both statements in the conditional, regardless of the results of .ContainsKey(). Then the userObject["lastlogon"] would throw an exception due to that key not existing in the dict and we'd be right back where we started.

Cheers!

**Comment by CCob** [comment]
Should be fine.  If statements with multiple conditions will stop at the first condition that guarantees the outcome won't change

**Comment by l0ss** [comment]
OK those conditionals have been combined - cheers for the review.

**Comment by 0xe7** [comment]
looks good to me, over to @HarmJ0y

**Review by HarmJ0y — APPROVED** [review]

**Comment by HarmJ0y** [comment]
Looks good to me, sorry for the delay!

**Pull request merged**
