### PR TITLE
Bruteforcing module

### PR DESCRIPTION
**Pull request by Zer1t0**
Hello, I create a bruteforcing module for Rubeus in command `brute`. 

As input this command accepts a file with passwords and a file with usernames, else if searchs with ldap for domain users. In this last case, domain credentials are accepted as input in order to perform the ldap. 

As output it indicates the valid passwords tested, save them in an result file (if given) and also store the obtained TGTs in files to use with `ptt` command.  Additionally, the module also inform of valid or invalid users detected (in case of input of file users) and blocked or disabled users.

### CODE REVIEW

**Comment by Ne0nd0g** [comment]
Consider changing `[X] You must supply some password! Use /password:<password> or /passwords:<file>` to something like `[X] You must supply a password! Use /password:<password> or /passwords:<file>` or `[X] A password was not provided! Use /password:<password> or /passwords:<file>`

**Comment by Ne0nd0g** [comment]
Unhandled exception when a domain is not provided:

```
C:\Users\russel\source\repos\Rubeus\Rubeus\bin\Debug>Rubeus.exe brute /password:

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


  [X] Error 1355 retrieving domain controller : The specified domain either does not exist or could not be contacted

[!] Unhandled Rubeus exception:

System.Runtime.InteropServices.COMException (0x80005000): Unknown error (0x80005000)
   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at Rubeus.Commands.Brute.DomainUsernames() in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Commands\Brute.cs:line 215
   at Rubeus.Commands.Brute.ObtainUsers() in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Commands\Brute.cs:line 178
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments) in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Commands\Brute.cs:line 43
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments) in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Domain\CommandCollection.cs:line 54
   at Rubeus.Program.Main(String[] args) in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Program.cs:line 24

C:\Users\russel\source\repos\Rubeus\Rubeus\bin\Debug>
```

**Comment by Ne0nd0g** [comment]
Unhandled error when an invalid domain is provided:

```
C:\Users\russel\source\repos\Rubeus\Rubeus\bin\Debug>Rubeus.exe brute /password: /domain:none.com

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[!] Unhandled Rubeus exception:

System.Runtime.InteropServices.COMException (0x8007203A): The server is not operational.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at Rubeus.Commands.Brute.DomainUsernames() in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Commands\Brute.cs:line 215
   at Rubeus.Commands.Brute.ObtainUsers() in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Commands\Brute.cs:line 178
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments) in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Commands\Brute.cs:line 43
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments) in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Domain\CommandCollection.cs:line 54
   at Rubeus.Program.Main(String[] args) in C:\Users\russel\Source\Repos\Rubeus\Rubeus\Program.cs:line 24

C:\Users\russel\source\repos\Rubeus\Rubeus\bin\Debug>
```

**Comment by Ne0nd0g** [comment]
Unhandled exception when a username is not provided from a domain joined host:

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[X] Administrator KRB-ERROR (14) : KDC_ERR_ETYPE_NOTSUPP

[-] Blocked/Disabled user => Guest
[-] Blocked/Disabled user => DefaultAccount
[-] Blocked/Disabled user => krbtgt

[X] unpriv2 KRB-ERROR (23) : KDC_ERR_KEY_EXPIRED


[!] Unhandled Rubeus exception:

Rubeus.KerberosErrorException
   at Rubeus.Bruteforcer.HandleKerberosError(KerberosErrorException ex, String username)
   at Rubeus.Bruteforcer.TestUsernamePassword(String username, String password)
   at Rubeus.Bruteforcer.Attack(String[] usernames, String[] passwords)
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.Main(String[] args)

C:\Users\unpriv3\Desktop>
```

**Comment by Ne0nd0g** [comment]
Consider adding an explicit statment when the brute force attack was not successful.

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password: /user:sql_svc

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2

[+] Valid user => sql_svc

C:\Users\unpriv3\Desktop>
```

**Comment by Ne0nd0g** [comment]
Unhandled exception when using a file that does not exist with the `/passwords` argument

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /passwords:C:\doesntexist.txt

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[!] Unhandled Rubeus exception:

System.IO.FileNotFoundException: Could not find file 'C:\doesntexist.txt'.
File name: 'C:\doesntexist.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path, Encoding encoding)
   at Rubeus.Commands.Brute.ParsePasswords(Dictionary`2 arguments)
   at Rubeus.Commands.Brute.ParseArguments(Dictionary`2 arguments)
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.Main(String[] args)

C:\Users\unpriv3\Desktop>
```

**Comment by Ne0nd0g** [comment]
Consider showing the `[-] Invalid user => Doesnt.Exist` message without the `/verbose` flag to be consistent with showing that a user does exist when the `/verbose` flag is not used.

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:password /user:Doesnt.Exist /verbose

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2

[-] Invalid user => Doesnt.Exist
```

**Comment by Ne0nd0g** [comment]
Unhandled exception when unable to resolve domain controller's FQDN:

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:password /user:sql_svc /dc:fake.com

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2

[X] Error resolving hostname 'fake.com' to an IP address: No such host is known

[!] Unhandled Rubeus exception:

Rubeus.RubeusException: [X] Unable to get domain controller address
   at Rubeus.Ask.InnerTGT(String userName, String domain, String keyString, KERB_ETYPE etype, Boolean ptt, String domainController, LUID luid, Boolean describe, Boolean verbose)
   at Rubeus.Bruteforcer.GetUsernamePasswordTGT(String username, String password)
   at Rubeus.Bruteforcer.TestUsernamePassword(String username, String password)
   at Rubeus.Bruteforcer.Attack(String[] usernames, String[] passwords)
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.Main(String[] args)

C:\Users\unpriv3\Desktop>
```

**Comment by Ne0nd0g** [comment]
Great use of the word `STUPENDOUS` when a brute force is successful:

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:password /user:sql_svc

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2

[+] STUPENDOUS => sql_svc:password
[*] Saved TGT into sql_svc.kirbi
```

**Comment by Ne0nd0g** [comment]
The `/domain` flag doesn't seem to process NETBIOS short names like `CORP` for `corp.rubeus.com`. Requires a FQDN.

**Comment by Ne0nd0g** [comment]
Unhandled exception when writing an outfile to a directory the user doesn't have permissions to:

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:password /user:sql_svc /verbose /outfile:C:\kerb.txt

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2

[+] STUPENDOUS => sql_svc:password

[!] Unhandled Rubeus exception:

System.UnauthorizedAccessException: Access to the path 'C:\kerb.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.AppendAllText(String path, String contents, Encoding encoding)
   at Rubeus.Commands.BruteforceConsoleReporter.WriteUserPasswordToFile(String username, String password)
   at Rubeus.Commands.BruteforceConsoleReporter.ReportValidPassword(String domain, String username, String password, Byte[] ticket)
   at Rubeus.Bruteforcer.ReportValidPassword(String username, String password, Byte[] ticket)
   at Rubeus.Bruteforcer.GetUsernamePasswordTGT(String username, String password)
   at Rubeus.Bruteforcer.TestUsernamePassword(String username, String password)
   at Rubeus.Bruteforcer.Attack(String[] usernames, String[] passwords)
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.Main(String[] args)

C:\Users\unpriv3\Desktop>
```

**Comment by Ne0nd0g** [comment]
Out message does not update `sql_svc.kirbi` to the file name provided with the `/outfile` argument. The outfile `test.kirbi` was successful written.

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:password /user:sql_svc /verbose /outfile:test.kirbi

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2

[+] STUPENDOUS => sql_svc:password
[*] Saved TGT into sql_svc.kirbi
```

**Comment by Ne0nd0g** [comment]
The `/outfile` flag does not write the TGT to the specified file. It writes the recovered username password pair. Not a problem, just a bad assumption on my part. Writing this as a statement.

outfile contents
```
sql_svc:password
```

**Comment by Ne0nd0g** [comment]
Unhandled error when specifying a fake/malformed OU with the `/ou` flag:

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:password /ou:fake

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[!] Unhandled Rubeus exception:

System.DirectoryServices.DirectoryServicesCOMException (0x80072032): An invalid dn syntax has been specified.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at Rubeus.Commands.Brute.DomainUsernames()
   at Rubeus.Commands.Brute.ObtainUsers()
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.Main(String[] args)

C:\Users\unpriv3\Desktop>
```

**Comment by Ne0nd0g** [comment]
Unhandled exception when a non-existent OU is provided with the `/ou` flag

```
C:\Users\unpriv3\Desktop>Rubeus.exe brute /password:password /ou:CN=FAKE,CN=Users,DC=corp,DC=rubeus,DC=com /verbose

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[!] Unhandled Rubeus exception:

System.DirectoryServices.DirectoryServicesCOMException (0x80072030): There is no such object on the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at Rubeus.Commands.Brute.DomainUsernames()
   at Rubeus.Commands.Brute.ObtainUsers()
   at Rubeus.Commands.Brute.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.Main(String[] args)
```

**Comment by Zer1t0** [comment]
Thank you for that exhaustive test. I resolved most of the issues commented in these previous commits.

However I was unable to reproduce the exception commented in https://github.com/GhostPack/Rubeus/pull/22#issuecomment-476676451, about lack of usernames in domain joined hosts.

Moreover, I decided to include `Invalid user` message only with `/verbose` flag because it could be annoying on large tests, so I think display only `Valid user` is fine. (This message is also supressed when users are recolected with an LDAP query due all the users should be valid)

Finally, I didn't included the option of NetBios name because it can't be resolved outside of the domain and could be a little tricky deal with both formats of domains in the same parameter (or separated ones).

I hope you like all this cleaning work.

**Comment by HarmJ0y** [comment]
Sorry for the (overly long) delay. This is awesome! Merging now.

**Pull request merged**
